version: '3'

services:

  db:
    image: postgres:15.2
    container_name: postgre-best-travel
    restart: always
    # /docker-entrypoint-initdb.d/ : Cuando el container se ejecute por primera vez buscará y ejecutará los scripts SQL indicados.
    volumes:
      - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - POSTGRES_DB=best_travel
      - POSTGRES_USER=rminaya
      - POSTGRES_PASSWORD=cibertec
    ports:
      - "5433:5432"