version: '3'
# Definimos los servicios/container para el PostgreSQL y Redis.
services:
  # 1°) Servicio para el PostgreSQL
  db:
    image: postgres:15.2
    container_name: postgre-best-travel
    restart: always
    # /docker-entrypoint-initdb.d/ : Cuando el container se ejecute por primera vez buscará y ejecutará los scripts SQL indicados.
    volumes:
      - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - POSTGRES_DB=best_travel
      - POSTGRES_USER=rminaya
      - POSTGRES_PASSWORD=cibertec
    ports:
      - "5433:5432"
  # 2°) Servicio para el servidor Redis
  cache:
    image: redis:6.2-alpine
    container_name: best_travel_cache
    restart: always
    ports:
     - "6379:6379"
     # Asignamos el nivel del logging como warning y la palabra "debuggeandoideas" como el password al servidor
    command: redis-server --loglevel warning --requirepass debuggeandoideas